[package]
name = "nuvae"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"
generational-arena = "0.2"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
internship = "0.6.0"
